### PR TITLE
chore: add semver []

### PR DESCRIPTION
**Pull request by kdamball**
## Purpose
Due to failures in releases in master - we should use the correct vault orb as other public repos

## Approach
semantic-release-ecosystem is the preferred way to go forward.

### CODE REVIEW

**Review by colomolo — APPROVED** [review]
Thanks!

**Comment by andipaetzold** [comment]
You need to update config.yml as well, right?

https://github.com/contentful/apps/blob/master/.circleci/config.yml#L11

**Comment by kdamball** [comment]
@andipaetzold you can only update that once `vault.yaml` changes are in master

**Comment by kdamball** [comment]
And `package.json`

**Comment by omasopust** [comment]
@kdamball We are seeing permission errors now in Vault for this project, is the usage change on the way?

**Comment by kdamball** [comment]
@omasopust follow up here: https://github.com/contentful/apps/pull/2467

**Pull request merged**
