### PR TITLE
fix: rename components to use multi-words and run linter

### PR DESCRIPTION
**Pull request by imretoth1999**
While using the example for the Vue contentful app I noticed that by default the linter is not working. 

Multi-Word-Component-Names is set to off to not cause a linter error when having the components Field, Page, Entry, etc. 
Another option would be to rename the components to use a multi-word but that would not keep the consistency across the other template examples.

Also, the files have been linted and committed to have the example following the best standards.

### CODE REVIEW

**Comment by colomolo** [comment]
Hi @imretoth1999 and thanks for your contribution. I think that rather than turning `vue/multi-word-component-names` off, it is better to adapt this template to follow Vue guidelines and rename components to be multi-worded. Your contribution with these changes would be more than welcome. Wdyt?

**Comment by imretoth1999** [comment]
Hello @colomolo. I'm glad you think the same about the eslint rule. I thought of renaming the files but wanted to keep the consistency between all of the examples in terms of naming but I agree that following the Vue standards is better. Each component has `Location` added in the name to describe its purpose better.

**Review by colomolo — APPROVED** [review]
Thanks, looks good!

**Review by andipaetzold — APPROVED** [review]

**Comment by andipaetzold** [comment]
Please adjust the title before merge as it is not accurate anymore

**Comment by imretoth1999** [comment]
> Please adjust the title before merge as it is not accurate anymore

Thank you for the approve, I changed the title of my PR

**Pull request merged**
